version: '2'

services:
  whitelabel-agen-backend-frontend:
    container_name: whitelabel-agen-backend-frontend
    image: whitelabel-agen-backend-frontend:0.0.1
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 2113:2113
    restart: always